Bump org.projectlombok:lombok from 1.18.24 to 1.18.36 (#2)
Bumps
[org.projectlombok:lombok](https://github.com/projectlombok/lombok) from
1.18.24 to 1.18.36.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/projectlombok/lombok/blob/master/doc/changelog.markdown">org.projectlombok:lombok's
changelog</a>.</em></p>
<blockquote>
<h3>v1.18.36 (November 15th, 2024)</h3>
<ul>
<li>PLATFORM: JDK23 support added.</li>
<li>BUGFIX: Eclipse projects using the
<code>com.pro-crafting.tools:jasperreports-maven-plugin</code> will now
compile.</li>
</ul>
<h3>v1.18.34 (June 28th, 2024)</h3>
<ul>
<li>PLATFORM: Added support for Eclipse 2024-06; you'd get some
<code>NoSuchMethodError</code> traces in your logs if using
<code>@Builder</code> or <code>@Singular</code> prior to this fix.
[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3638">#3638</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3638">projectlombok/lombok#3638</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: Lombok now adds
<code>@lombok.Generated</code> by default to methods and types it
generates. This may result in accidentally increasing your test coverage
percentage. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3667">#3667</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3667">projectlombok/lombok#3667</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: When <code>lombok.config</code> contains
<code>lombok.onX.flagUsage = WARNING</code>, from now on warnings will
actually be generated if onX is used.[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/2848">#2848</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/2848">projectlombok/lombok#2848</a>)</li>
<li>BUGFIX: When <code>@SuperBuilder</code> was used on a type with an
generic array type, it would error <code>wrong number of type
arguments</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3694">#3694</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3694">projectlombok/lombok#3694</a>).</li>
<li>FEATURE: Lombok generates javadoc for you for most of the methods it
adds; with this release, javadoc is also added to generated
constructors. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/933">#933</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/933">projectlombok/lombok#933</a>).</li>
</ul>
<h3>v1.18.32 (March 20th, 2024)</h3>
<ul>
<li>PLATFORM: Initial JDK22 support added.</li>
<li>PLAFTORM Added support for Eclipse 2024-03. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">#3620</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">projectlombok/lombok#3620</a>).</li>
<li>PLATFORM: Added support for recent versions of eclipse (released Q4
2023 or later or so) which would cause failures in the eclipse logs such
as <code>java.lang.NoSuchMethodError: 'java.lang.StringBuffer
org.eclipse.jdt…</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">#3564</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">projectlombok/lombok#3564</a>).</li>
<li>FEATURE: <code>@Locked</code> has been introduced. Like
<code>@Synchronized</code> but with
<code>java.util.concurrent.locks</code> locks instead of the
<code>synchronized</code> primitive. Thanks, Pim van der Loos for the
PR! [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">#3506</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">projectlombok/lombok#3506</a>).</li>
<li>NECROMANCY: Inlining a generated getter in eclipse would result in
eclipse incorrectly replacing calls with <code>@Getter</code> instead of
the actual field's name. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/562">#562</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/562">projectlombok/lombok#562</a>).
This issue is almost old enough to drink. Points for dedication go to
Rawi for fixing this one.</li>
<li>BUGFIX: When <code>@SuperBuilder</code> was used on a type with an
annotated generic type, it would error <code>wrong number of type
arguments</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">#3592</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">projectlombok/lombok#3592</a>).</li>
<li>BUGFIX: It was possible to create an infinite build loop using
<code>@ExtensionMethod</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">#3225</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">projectlombok/lombok#3225</a>).</li>
<li>BUGFIX: Using <code>@Getter(lazy=true)</code> would fail if the
expression contained a variable called <code>value</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">#2917</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">projectlombok/lombok#2917</a>).</li>
<li>BUGFIX: Many lombok features wouldn't work properly on records
contained within an outer type unless you explicitly marked it
<code>static</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">#3497</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">projectlombok/lombok#3497</a>)
[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">#3559</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">projectlombok/lombok#3559</a>).</li>
<li>BUGFIX: Eclipse projects using the
<code>com.pro-crafting.tools:jasperreports-plugin</code> will now
compile.</li>
<li>BUGFIX: <code>@FieldNameConstants</code> now works when generated
fields are involved. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">#3529</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">projectlombok/lombok#3529</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: For JSpecify, the package name changed
from <code>org.jspecify.nullness</code> to
<code>org.jspecify.annotations</code>, which might lead to a different
null analysis. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3608">#3608</a>](<a
href="https://redirect.github.com/projectlombok/lombok/pull/3608">projectlombok/lombok#3608</a>).</li>
</ul>
<h3>v1.18.30 (September 20th, 2023)</h3>
<ul>
<li>PLATFORM: Initial JDK21 support added. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3393">#3393</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3393">projectlombok/lombok#3393</a>).</li>
<li>BUGFIX: Any <code>@Helper</code> class directly in a method (and not
nested more deeply) wouldn't work. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3370">#3370</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3370">projectlombok/lombok#3370</a>).</li>
<li>BUGFIX: If using the module system and lombok is on the runtime
classpath (shouldn't be, but happens), you'd get a split package error:
<code>Package org.objectweb.asm in both module lombok and module
org.objectweb.asm</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3474">#3474</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3474">projectlombok/lombok#3474</a>).</li>
<li>BUGFIX: Lombok wasn't properly copying the annotations it should be
copying when generating methods in <code>record</code>s. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3315">#3315</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3315">projectlombok/lombok#3315</a>).</li>
<li>BUGFIX: Delomboking anything with <code>@lombok.Singular</code> in
it wouldn't remove that annotation. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/1377">#1377</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/1377">projectlombok/lombok#1377</a>).</li>
<li>BUGFIX: Calling extension methods such that automatic widening is
applied (i.e. calling <code>void ext(long arg)</code> with an
<code>int</code>) would fail at runtime. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3463">#3463</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3463">projectlombok/lombok#3463</a>).</li>
<li>BUGFIX: Extension methods can now be used in records. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3450">#3450</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3450">projectlombok/lombok#3450</a>).</li>
<li>BUGFIX: <code>@Getter(lazy=true)</code> with complicated
initialization expressions would fail on javac. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3314">#3314</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3314">projectlombok/lombok#3314</a>).</li>
<li>BUGFIX: Using the maven surefire plugin with a
<code>module-info.java</code> based project would fail with a
<code>SurefireBooterForkException</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3474">#3474</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3474">projectlombok/lombok#3474</a>).</li>
</ul>
<h3>v1.18.28 (May 24th, 2023)</h3>
<ul>
<li>PLATFORM: JDK20 support added. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3353">#3353</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3353">projectlombok/lombok#3353</a>).</li>
<li>BUGFIX: Eclipse 4.27 and VSCode 1.14.0 would ignore
<code>lombok.config</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3332">#3332</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3332">projectlombok/lombok#3332</a>).</li>
<li>BUGFIX: <code>@NonNull</code> on a primitive array field on a record
wouldn't work. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3366">#3366</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3366">projectlombok/lombok#3366</a>).</li>
<li>FEATURE: Jakarta has some non-null annotations (such as
<code>jakarta.annotation.Nonnull</code>) which we now support. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3346">#3346</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3346">projectlombok/lombok#3346</a>).</li>
<li>BUGFIX: Eclipse didn't find usages of extension methods
(<code>@ExtensionMethod</code>) in &quot;find references&quot; nor
rename-refactoring. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3373">#3373</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3373">projectlombok/lombok#3373</a>)</li>
</ul>
<h3>v1.18.26 (Feb 3rd, 2023)</h3>
<ul>
<li>PLATFORM: JDK19 support added. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3264">#3264</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3264">projectlombok/lombok#3264</a>).</li>
<li>BUGFIX: Using the refactor script: &quot;Rename field&quot; in a
<code>@(Super)Builder</code>-marked file in eclipse or VSCode would
cause issues. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3181">#3181</a>]
(<a
href="https://redirect.github.com/projectlombok/lombok/issues/3181">projectlombok/lombok#3181</a>).</li>
<li>BUGFIX: Using <code>val</code> together with any call to a method
that explicitly resolves to a default impl in an interface didn't work
in javac. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3242">#3242</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3242">projectlombok/lombok#3242</a>).</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/projectlombok/lombok/commit/91d79ff9fbef24494039a9f37498a4fd4386459e"><code>91d79ff</code></a>
[release] pre-release version bump</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/e8db33a77042dd3429b3e10f68109e45ea6251cc"><code>e8db33a</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3768">#3768</a>
from tamila-krashtan/fix/with-html</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/033870592900e47d9855d190924d0addecddad61"><code>0338705</code></a>
Revert &quot;[fixes <a
href="https://redirect.github.com/projectlombok/lombok/issues/3116">#3116</a>]
Add multi round support for mapstruct&quot;:</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/9af596e29ecb0375d3474e4de7299cb21ecadbd6"><code>9af596e</code></a>
Fix typo in With.html</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/3394b6ef7c00b25ad4ad4b64ac5f879aa16e4db5"><code>3394b6e</code></a>
eclipse downloader: When downloading sources, accept failure.</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/03cd61a9ec179689830fb948308ee2a92e554011"><code>03cd61a</code></a>
Merge branch 'eclipse-tests-fix'</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/7a9f3a8b7599d4be61bd32698874f6d7e4c15b89"><code>7a9f3a8</code></a>
Fix resource management in the eclipse downloader:</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/87bc91a95a1f399230cb0d85d3f8082d90e9a9a6"><code>87bc91a</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3764">#3764</a>
from Rawi01/update-index</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/d21d551a4dab3ec88c968761fbd3c62bab27fb2a"><code>d21d551</code></a>
Close ZipOutputStream in eclipse dependency downloader</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/5caea325100c2b76dee6a5d63c1328523a9da671"><code>5caea32</code></a>
[fixes <a
href="https://redirect.github.com/projectlombok/lombok/issues/3761">#3761</a>]
Update annotation value index</li>
<li>Additional commits viewable in <a
href="https://github.com/projectlombok/lombok/compare/v1.18.24...v1.18.36">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.projectlombok:lombok&package-manager=gradle&previous-version=1.18.24&new-version=1.18.36)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>